# Generated by Django 2.0.2 on 2018-04-07 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smfreal', '0002_auto_20180403_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrecord',
            name='name',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
