# Generated by Django 2.0.2 on 2018-04-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smfreal', '0003_auto_20180408_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='fundlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundcompany', models.CharField(max_length=200)),
                ('fundtype', models.CharField(max_length=200)),
                ('fundname', models.CharField(max_length=200)),
                ('fundlaunchdate', models.CharField(max_length=200)),
                ('fundno', models.CharField(max_length=200)),
                ('fundreturn', models.CharField(max_length=200)),
            ],
        ),
    ]
