# Generated by Django 2.0.2 on 2018-04-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smfreal', '0004_fundlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='fundlist',
            name='fundno',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
