# Generated by Django 2.0.2 on 2018-04-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smfreal', '0007_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
