# Generated by Django 2.0.2 on 2018-04-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smfreal', '0008_userprofileinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundlist',
            name='fundcomimagepath',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
