# Generated by Django 2.0.2 on 2018-04-09 20:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('smfreal', '0012_auto_20180410_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myuserdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myusername', models.CharField(max_length=20)),
                ('user_full_name', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=200)),
                ('user_pan_card', models.CharField(max_length=200)),
                ('user_bank_ifsc', models.CharField(max_length=200)),
                ('user_bank_account_no', models.CharField(max_length=15)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 4, 9, 20, 0, 45, 280524, tzinfo=utc))),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 9, 20, 0, 45, 280524, tzinfo=utc)),
        ),
    ]
