# Generated by Django 2.0.2 on 2018-04-09 20:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('smfreal', '0013_auto_20180410_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuserdb',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='myuserdb',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 9, 20, 3, 6, 570465, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 9, 20, 3, 6, 570465, tzinfo=utc)),
        ),
    ]
