# Generated by Django 2.0.2 on 2018-04-09 20:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('smfreal', '0017_auto_20180410_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuserdb',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 9, 20, 7, 4, 891541, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 9, 20, 7, 4, 891541, tzinfo=utc)),
        ),
    ]
