# Generated by Django 2.0.2 on 2018-04-09 21:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('smfreal', '0019_auto_20180410_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundlist',
            name='fundreturn',
        ),
        migrations.AddField(
            model_name='fundlist',
            name='fundNAV',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fundlist',
            name='fundexpenseratio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fundlist',
            name='fundminimumInvest',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fundlist',
            name='fundminimumSIP',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fundlist',
            name='fundportfolio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fundlist',
            name='fundrating',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fundlist',
            name='fundreturn_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fundlist',
            name='fundreturn_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fundlist',
            name='fundreturn_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fundlist',
            name='fundreturn_5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fundlist',
            name='fundrisk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myuserdb',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 9, 21, 8, 7, 796649, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 9, 21, 8, 7, 796649, tzinfo=utc)),
        ),
    ]
